format = "$character$all"

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "fg:#F1DFAF"
style_root = "fg:#DCA3A3"
format = '[$user]($style bold) in'

[directory]
read_only = " ï ½"
style = "fg:#DCDCCC bold"
format = "[ $path]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[hostname]
ssh_symbol = "ï¦Œ "
[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "
style = "fg:#9ECE9E"
format = '[ $symbol ($version) ]($style)'

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "
style = "fg:#9ECE9E"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "î‰µ "
style = "fg:#9ECE9E"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "fg:#9ECE9E"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜ "
style = "fg:#86AD86 bold"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#CC9393 bold"
format = '[($all_status$ahead_behind )]($style)'

[golang]
symbol = "î˜§ "
style = "fg:#9ECE9E"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "fg:#9ECE9E"
format = '[ $symbol ($version) ]($style)'

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "
style = "fg:#9ECE9E"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "fg:#9ECE9E"
format = '[ $symbol ($version) ]($style)'

[memory_usage]
symbol = "ï¡š "

[nodejs]
symbol = "îœ˜ "
style = "fg:#9ECE9E"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ïš¤ "
style = "fg:#9ECE9E"
format = '[ $symbol ($version) ]($style)'

[nix_shell]
symbol = "ï‹œ "

[package]
symbol = "ï£– "

[python]
symbol = "îˆµ "
style = "fg:#9ECE9E"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨ "
style = "fg:#9ECE9E"
format = '[ $symbol ($version) ]($style)'

[spack]
symbol = "ğŸ…¢ "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#DCDCCC bold"
format = 'at [$time ]($style)'

[line_break]
disabled = true

[character]
format = "$symbol"
error_symbol = "[Iï—…](bold fg:#D78787) "
success_symbol = "[Iï—€](bold fg:#87D787) "
vimcmd_symbol = "[Nï–¿](bold fg:#87AFAF) "
vimcmd_visual_symbol = "[Vï–¿](bold fg:#FFD7AF) "
vimcmd_replace_symbol = "[Rï—„](bold fg:#D78787) "
vimcmd_replace_one_symbol = "[Cï—„](bold fg:#D78787) "
